### ISSUE TITLE
Problem when building for android platform

### ISSUE THREAD

**Issue by duyquang957** [edricwilliem/unity-firebase-realtime-database#3]
Hello thanks for sharing, your library is helpful. But when  I try bulding on android for test with il2cpp in unity 2019.4.10(lts) get error below.
```
Failed running C:\Program Files\Unity\Hub\Editor\2019.4.10f1\Editor\Data\il2cpp/build/deploy/net471/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="D:\UnityProject\unity-firebase-realtime-database-master\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="D:\UnityProject\unity-firebase-realtime-database-master\Assets\..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2019.4.10f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2019.4.10f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="C:/Program Files/Unity/Hub/Editor/2019.4.10f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --profiler-report --map-file-parser="C:/Program Files/Unity/Hub/Editor/2019.4.10f1/Editor/Data/Tools/MapFileParser/MapFileParser.exe" --directory=D:/UnityProject/unity-firebase-realtime-database-master/Temp/StagingArea/assets/bin/Data/Managed --generatedcppdir=D:/UnityProject/unity-firebase-realtime-database-master/Temp/StagingArea/Il2Cpp/il2cppOutput 

stdout:
Building libil2cpp.so with AndroidToolChain
	Output directory: D:\UnityProject\unity-firebase-realtime-database-master\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a
	Cache directory: D:\UnityProject\unity-firebase-realtime-database-master\Library\il2cpp_android_armeabi-v7a\il2cpp_cache
ObjectFiles: 125 of which compiled: 0
Total compilation time: 79 milliseconds.
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Program Files\Unity\Hub\Editor\2019.4.10f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\MSI\AppData\Local\Temp\tmp24D6.tmp" -o "D:\UnityProject\unity-firebase-realtime-database-master\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_814CE8AB18E11C9D9399614D11C10624\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target armv7-linux-androideabi19 -Wl,--wrap,sigaction -llog -rdynamic -fuse-ld=gold.exe

D:\UnityProject\unity-firebase-realtime-database-master\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp.cpp:18125: error: undefined reference to 'CloseEventSource'
D:\UnityProject\unity-firebase-realtime-database-master\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp.cpp:18110: error: undefined reference to 'CreateEventSource'
D:\UnityProject\unity-firebase-realtime-database-master\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp.cpp:18125: error: undefined reference to 'CloseEventSource'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)


   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args, List`1 foundAssemblies)
   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Program Files\Unity\Hub\Editor\2019.4.10f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\MSI\AppData\Local\Temp\tmp24D6.tmp" -o "D:\UnityProject\unity-firebase-realtime-database-master\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_814CE8AB18E11C9D9399614D11C10624\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target armv7-linux-androideabi19 -Wl,--wrap,sigaction -llog -rdynamic -fuse-ld=gold.exe

D:\UnityProject\unity-firebase-realtime-database-master\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp.cpp:18125: error: undefined reference to 'CloseEventSource'
D:\UnityProject\unity-firebase-realtime-database-master\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp.cpp:18110: error: undefined reference to 'CreateEventSource'
D:\UnityProject\unity-firebase-realtime-database-master\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp.cpp:18125: error: undefined reference to 'CloseEventSource'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)


   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args, List`1 foundAssemblies)
   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture)
   at il2cpp.Program.Main(String[] args)

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunProgram(Program, String, String, String, CompilerOutputParserBase)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase, Action`1)
UnityEditorInternal.IL2CPPBuilder:RunIl2CppWithArguments(List`1, Action`1, String)
UnityEditorInternal.IL2CPPBuilder:ConvertPlayerDlltoCpp(Il2CppBuildPipelineData, String, String, Boolean)
UnityEditorInternal.IL2CPPBuilder:Run()
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by duyquang957** [comment]
I have remove 'CreateEventSource' and 'CloseEventSource' in FirebaseDatabase.cs and it work. I don't know what functions it does. but I hope that functions will fixes in next release.
